



var form0101= null;
var form0102= null;
var form0103= `<form><div class="image-form-question--image-container--3HTvR" style="position: relative;"><img src="https://lh6.ggpht.com/4F9okwFNAQRqIg37kC6dunDssPf4HrK1wwGhse4Il4yIWuaq1Ahbo1uoZS5Q49G0gE5Me3WvzPplmzkX_QU=s0#w=1920&amp;h=1080" style="width: 100%; max-height: 100%;"><div style="top: 68.6856%; left: 8.72872%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-0" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-0" class="radio-button-widget--radio--ws3E_" value="0"></span></div><div style="top: 60.3737%; left: 8.29409%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-1" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-1" class="radio-button-widget--radio--ws3E_" value="1"></span></div><div style="top: 52.2552%; left: 8.40275%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-2" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-2" class="radio-button-widget--radio--ws3E_" value="2"></span></div><div style="top: 44.7165%; left: 8.29409%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-3" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-3" class="radio-button-widget--radio--ws3E_" value="3"></span></div><div style="top: 37.1778%; left: 8.18544%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-4" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-4" class="radio-button-widget--radio--ws3E_" value="4"></span></div></div></form>`;
form0103= ` <form>
   <div style="position: relative;">
   <img src="quiz01/0103.jpg#w=1920&amp;h=1080" style="width: 100%; max-height: 100%;">
   <div style="top: 64.6856%; left: 1.72872%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;">
   <span>
   <label for="radio-0">yellow</label>
   <input type="radio" id="radio-0" value="0">
   </span>
   </div>
   <div style="top: 56.3737%; left: 1.29409%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;">
   <span>
   <label for="radio-1">orange</label>
   <input type="radio" id="radio-1" value="1">
   </span>
   </div>
   <div style="top: 48.2552%; left: 1.40275%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;">
   <span>
   <label for="radio-2">green</label>
   <input type="radio" id="radio-2" value="2">
   </span>
   </div>
   <div style="top: 40.7165%; left: 1.29409%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;">
   <span>
   <label for="radio-3">blue</label>
   <input type="radio" id="radio-3" value="3" checked>
   </span>
   </div>
   <div style="top: 33.1778%; left: 1.18544%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;">
   <span>
   <label for="radio-4">red</label>
   <input type="radio" id="radio-4" value="4">
   </span>
   </div>
   </div>
</form>`;
var form0104= `<form><div class="image-form-question--image-container--3HTvR" style="position: relative;"><img src="https://lh5.ggpht.com/Z2fbxIdswomz1BLwFhblxPwFpfDkrHs-2Q8HoR8549CM-vLMeCPVZiT04YSBmQKJH9GV4EdLYSr0eNqCPMU=s0#w=1920&amp;h=1080" style="width: 100%; max-height: 100%;"><div style="top: 33.8918%; left: 9.59797%; position: absolute; width: 14.7132%; height: 6.65188%;"><span class="text-input-widget--container--2JE4b"><label for="text-0" class="text-input-widget--label--D9NOV">Empty</label><input name="0" type="text" id="text-0" class="text-input-widget--text-input--4-Mx-" value="no" style="width: 100%; height: 100%;"></span></div></div></form>`;
var form0105= null;
var form0106= `<form><div class="image-form-question--image-container--3HTvR" style="position: relative;"><img src="https://lh3.ggpht.com/ManDj2bNHJTy7OUyoUb90yYQwEz3IkFK5vcTPY_mHcXQ3T7VEXiX68tP7FMl7QHR1RZbE20F74PHKjAcVfU=s0#w=1920&amp;h=1080" style="width: 100%; max-height: 100%;"><div style="top: 27.3196%; left: 40.239%; position: absolute; width: 15%; height: 6%;"><span class="text-input-widget--container--2JE4b"><label for="text-0" class="text-input-widget--label--D9NOV">Empty</label><input name="0" type="text" id="text-0" class="text-input-widget--text-input--4-Mx-" value="4.74" style="width: 100%; height: 100%;"></span></div></div></form>`;
var form0107= `<form><div class="image-form-question--image-container--3HTvR" style="position: relative;"><img src="https://lh4.ggpht.com/fdrgzPLLHohvtM_oKTV84iRU1q9VlGRUzuYO0lkkDei6X5urafHSmTs5YDrswDKwkBvnilRcMzP1pzweeKI3=s0#w=1920&amp;h=1080" style="width: 100%; max-height: 100%;"><div style="top: 41.2371%; left: 9.81528%; position: absolute; width: 21.8399%; height: 6.37887%;"><span class="text-input-widget--container--2JE4b"><label for="text-0" class="text-input-widget--label--D9NOV">Empty</label><input name="0" type="text" id="text-0" class="text-input-widget--text-input--4-Mx-" value="statistics" style="width: 100%; height: 100%;"></span></div><div style="top: 41.4304%; left: 39.8044%; position: absolute; width: 19.5581%; height: 6.18557%;"><span class="text-input-widget--container--2JE4b"><label for="text-1" class="text-input-widget--label--D9NOV">Empty</label><input name="1" type="text" id="text-1" class="text-input-widget--text-input--4-Mx-" value="is" style="width: 100%; height: 100%;"></span></div><div style="top: 41.817%; left: 70.7715%; position: absolute; width: 19.2322%; height: 5.99227%;"><span class="text-input-widget--container--2JE4b"><label for="text-2" class="text-input-widget--label--D9NOV">Empty</label><input name="2" type="text" id="text-2" class="text-input-widget--text-input--4-Mx-" value="awesome" style="width: 100%; height: 100%;"></span></div></div></form>`;
var form0108= null;
var form0109= `<form><div class="image-form-question--image-container--3HTvR" style="position: relative;"><img src="https://lh5.ggpht.com/rmxx5urNWtqdaQdwhXN-U6_atEUltlc8EGY7zx1FUrjJWwa9OuJ7UBQ111BSq4AaWfxWecydlZAOwUSl1Bw=s0#w=1920&amp;h=1080" style="width: 100%; max-height: 100%;"><div style="top: 14.7552%; left: 29.1561%; position: absolute; width: 9.97506%; height: 5.54324%;"><span class="text-input-widget--container--2JE4b"><label for="text-0" class="text-input-widget--label--D9NOV">Empty</label><input name="0" type="text" id="text-0" class="text-input-widget--text-input--4-Mx-" value="" style="width: 100%; height: 100%;"></span></div><div style="top: 15.1671%; left: 43.4153%; position: absolute; width: 8.97756%; height: 5.54324%;"><span class="text-input-widget--container--2JE4b"><label for="text-1" class="text-input-widget--label--D9NOV">Empty</label><input name="1" type="text" id="text-1" class="text-input-widget--text-input--4-Mx-" value="" style="width: 100%; height: 100%;"></span></div></div></form>`;
var form0110= `<form><div class="image-form-question--image-container--3HTvR" style="position: relative;"><img src="https://lh6.ggpht.com/TQoQ1vdBkJ7t1tE48PBRYqJqadVKWG8s2oSIUSt5_N4dFAU7FI87ebdgxA8d7oj5iR0blcC2uRTDOLv9Ww=s0#w=1920&amp;h=1080" style="width: 100%; max-height: 100%;"><div style="top: 64.6263%; left: 22.4194%; position: absolute; width: 16.4589%; height: 7.31707%;"><span class="text-input-widget--container--2JE4b"><label for="text-0" class="text-input-widget--label--D9NOV">Empty</label><input name="0" type="text" id="text-0" class="text-input-widget--text-input--4-Mx-" value="" style="width: 100%; height: 100%;"></span></div><div style="top: 73.3247%; left: 22.6367%; position: absolute; width: 16.3342%; height: 6.43016%;"><span class="text-input-widget--container--2JE4b"><label for="text-1" class="text-input-widget--label--D9NOV">Empty</label><input name="1" type="text" id="text-1" class="text-input-widget--text-input--4-Mx-" value="" style="width: 100%; height: 100%;"></span></div><div style="top: 82.0232%; left: 22.4194%; position: absolute; width: 16.3342%; height: 5.9867%;"><span class="text-input-widget--container--2JE4b"><label for="text-2" class="text-input-widget--label--D9NOV">Empty</label><input name="2" type="text" id="text-2" class="text-input-widget--text-input--4-Mx-" value="" style="width: 100%; height: 100%;"></span></div></div></form>`;
var form0111= null;
var form01= [ form0101, form0102, form0103, form0104, form0105, form0106, form0107, form0108, form0109, form0110, form0111 ];


var form0201= `<form><div class="image-form-question--image-container--3HTvR" style="position: relative;"><img src="https://lh3.googleusercontent.com/C4Oox2X2yqDzfmYZJkYF6S998iSOAFcsiGz9rgItr2DUJEGZuDe_churRjzxlgtwj8M9bFecNtA3qjmrk7Y=s0#w=774&amp;h=436" style="width: 100%; max-height: 100%;"><div style="top: 26.2646%; left: 64.6626%; position: absolute; width: 5%; height: 5%; max-width: 15px; max-height: 15px;"><span><label for="radio-radio1" class="radio-button-widget--label--vDh18"></label><input type="radio" name="group0" id="radio-radio1" class="radio-button-widget--radio--ws3E_" value="radio1"></span></div><div style="top: 41.0096%; left: 64.6275%; position: absolute; width: 5%; height: 5%; max-width: 15px; max-height: 15px;"><span><label for="radio-radio2" class="radio-button-widget--label--vDh18"></label><input type="radio" name="group0" id="radio-radio2" class="radio-button-widget--radio--ws3E_" value="radio2"></span></div><div style="top: 56.1946%; left: 64.9373%; position: absolute; width: 5%; height: 5%; max-width: 15px; max-height: 15px;"><span><label for="radio-radio3" class="radio-button-widget--label--vDh18"></label><input type="radio" name="group0" id="radio-radio3" class="radio-button-widget--radio--ws3E_" value="radio3"></span></div><div style="top: 71.286%; left: 64.871%; position: absolute; width: 5%; height: 5%; max-width: 15px; max-height: 15px;"><span><label for="radio-radio4" class="radio-button-widget--label--vDh18"></label><input type="radio" name="group0" id="radio-radio4" class="radio-button-widget--radio--ws3E_" value="radio4"></span></div><div style="top: 87.0184%; left: 65.3815%; position: absolute; width: 5%; height: 5%; max-width: 15px; max-height: 15px;"><span><label for="radio-radio5" class="radio-button-widget--label--vDh18"></label><input type="radio" name="group0" id="radio-radio5" class="radio-button-widget--radio--ws3E_" value="radio5"></span></div></div></form>`;
var form0202= `<form><div class="image-form-question--image-container--3HTvR" style="position: relative;"><img src="https://lh3.googleusercontent.com/GSoqbJXlXJnyJ3CQd-LjBPdwcqZlUyFzLyKL9i29BgmOaibXIH3LP-ZraWsk72qnMW-sX6igd12_qOR5dik=s0#w=774&amp;h=436" style="width: 100%; max-height: 100%;"><div style="top: 25.1143%; left: 50.3156%; position: absolute; width: 5%; height: 5%; max-width: 15px; max-height: 15px;"><span><label for="radio-radio1" class="radio-button-widget--label--vDh18"></label><input type="radio" name="group0" id="radio-radio1" class="radio-button-widget--radio--ws3E_" value="radio1"></span></div><div style="top: 39.4055%; left: 51.1748%; position: absolute; width: 5%; height: 5%; max-width: 15px; max-height: 15px;"><span><label for="radio-radio2" class="radio-button-widget--label--vDh18"></label><input type="radio" name="group0" id="radio-radio2" class="radio-button-widget--radio--ws3E_" value="radio2"></span></div><div style="top: 54.3618%; left: 51.4846%; position: absolute; width: 5%; height: 5%; max-width: 15px; max-height: 15px;"><span><label for="radio-radio3" class="radio-button-widget--label--vDh18"></label><input type="radio" name="group0" id="radio-radio3" class="radio-button-widget--radio--ws3E_" value="radio3"></span></div><div style="top: 69.6716%; left: 51.7495%; position: absolute; width: 5%; height: 5%; max-width: 15px; max-height: 15px;"><span><label for="radio-radio4" class="radio-button-widget--label--vDh18"></label><input type="radio" name="group0" id="radio-radio4" class="radio-button-widget--radio--ws3E_" value="radio4"></span></div><div style="top: 86.038%; left: 52.0944%; position: absolute; width: 5%; height: 5%; max-width: 15px; max-height: 15px;"><span><label for="radio-radio5" class="radio-button-widget--label--vDh18"></label><input type="radio" name="group0" id="radio-radio5" class="radio-button-widget--radio--ws3E_" value="radio5"></span></div></div></form>`;
var form0203= `<form><div class="image-form-question--image-container--3HTvR" style="position: relative;"><img src="https://lh3.googleusercontent.com/qAY4kul6ZsOGPrZ9sJNM-w5BqAwC91kCIsnbEaysiUn9M1wy750TT-uX5j7-EKI_Kbg_65l61t351Dchzg=s0#w=774&amp;h=436" style="width: 100%; max-height: 100%;"><div style="top: 47.1037%; left: 47.9076%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-0" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-0" class="radio-button-widget--radio--ws3E_" value="0"></span></div><div style="top: 32.8541%; left: 84.1295%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-1" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-1" class="radio-button-widget--radio--ws3E_" value="1"></span></div><div style="top: 87.6109%; left: 43.5162%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-2" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-2" class="radio-button-widget--radio--ws3E_" value="2"></span></div><div style="top: 87.7529%; left: 70.6359%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-3" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-3" class="radio-button-widget--radio--ws3E_" value="3"></span></div></div></form>`;
var form0204= `<form><div class="image-form-question--image-container--3HTvR" style="position: relative;"><img src="https://lh3.googleusercontent.com/dWLUnF0H_4TTdaww1mbHvFmMuy94ltUhde64Gbd2j2mWoIwkNFOgvHFlfFhZ587ZyJjaV5jqdryDp51FesQ=s0#w=774&amp;h=436" style="width: 100%; max-height: 100%;"><div style="top: 24.7298%; left: 51.7924%; position: absolute; width: 5%; height: 5%; max-width: 15px; max-height: 15px;"><span><label for="radio-radio1" class="radio-button-widget--label--vDh18"></label><input type="radio" name="group0" id="radio-radio1" class="radio-button-widget--radio--ws3E_" value="radio1"></span></div><div style="top: 40.8675%; left: 51.5956%; position: absolute; width: 5%; height: 5%; max-width: 15px; max-height: 15px;"><span><label for="radio-radio2" class="radio-button-widget--label--vDh18"></label><input type="radio" name="group0" id="radio-radio2" class="radio-button-widget--radio--ws3E_" value="radio2"></span></div><div style="top: 55.5813%; left: 52.2093%; position: absolute; width: 5%; height: 5%; max-width: 15px; max-height: 15px;"><span><label for="radio-radio3" class="radio-button-widget--label--vDh18"></label><input type="radio" name="group0" id="radio-radio3" class="radio-button-widget--radio--ws3E_" value="radio3"></span></div><div style="top: 70.0527%; left: 52.2249%; position: absolute; width: 5%; height: 5%; max-width: 15px; max-height: 15px;"><span><label for="radio-radio4" class="radio-button-widget--label--vDh18"></label><input type="radio" name="group0" id="radio-radio4" class="radio-button-widget--radio--ws3E_" value="radio4"></span></div><div style="top: 86.6165%; left: 52.1197%; position: absolute; width: 5%; height: 5%; max-width: 15px; max-height: 15px;"><span><label for="radio-radio5" class="radio-button-widget--label--vDh18"></label><input type="radio" name="group0" id="radio-radio5" class="radio-button-widget--radio--ws3E_" value="radio5"></span></div></div></form>`;
var form0205= `<form><div class="image-form-question--image-container--3HTvR" style="position: relative;"><img src="https://lh5.ggpht.com/pwUo0mxWN9WunfGxTCVGxvGrWRRE7cINo2QDBKM7lSdKYHrxVsJ9Z5Fu5i-ZE0N1-M3rH1KmWkkuerM0Fnc=s0#w=1280&amp;h=720" style="width: 100%; max-height: 100%;"><div style="top: 45.2964%; left: 52.0826%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-0" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-0" class="radio-button-widget--radio--ws3E_" value="0"></span></div><div style="top: 36.4046%; left: 51.9739%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-1" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-1" class="radio-button-widget--radio--ws3E_" value="1"></span></div><div style="top: 45.4253%; left: 36.0377%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-2" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-2" class="radio-button-widget--radio--ws3E_" value="2"></span></div><div style="top: 35.8247%; left: 36.1101%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-3" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-3" class="radio-button-widget--radio--ws3E_" value="3"></span></div></div></form>`;
var form0206= `<form><div class="image-form-question--image-container--3HTvR" style="position: relative;"><img src="https://lh5.ggpht.com/jya7bX7_itVW63lAwJA3hrTZcjRRncH0n0MW6ETHXQQUQ_arHnd77OSOm-YX7htiLhxvput_p2sJ_OTtfbA2=s0#w=1280&amp;h=720" style="width: 100%; max-height: 100%;"><div style="top: 52.6992%; left: 41.3893%; position: absolute; width: 17.9551%; height: 5.54324%;"><span class="text-input-widget--container--2JE4b"><label for="text-0" class="text-input-widget--label--D9NOV">Empty</label><input name="0" type="text" id="text-0" class="text-input-widget--text-input--4-Mx-" value="A1" style="width: 100%; height: 100%;"></span></div><div style="top: 61.7268%; left: 77.9428%; position: absolute; width: 17.0823%; height: 5.54324%;"><span class="text-input-widget--container--2JE4b"><label for="text-1" class="text-input-widget--label--D9NOV">Empty</label><input name="1" type="text" id="text-1" class="text-input-widget--text-input--4-Mx-" value="C3" style="width: 100%; height: 100%;"></span></div><div style="top: 66.581%; left: 59.6237%; position: absolute; width: 17.8304%; height: 5.54324%;"><span class="text-input-widget--container--2JE4b"><label for="text-2" class="text-input-widget--label--D9NOV">Empty</label><input name="2" type="text" id="text-2" class="text-input-widget--text-input--4-Mx-" value="B4" style="width: 100%; height: 100%;"></span></div><div style="top: 75.8355%; left: 41.3893%; position: absolute; width: 17.9551%; height: 5.54324%;"><span class="text-input-widget--container--2JE4b"><label for="text-3" class="text-input-widget--label--D9NOV">Empty</label><input name="3" type="text" id="text-3" class="text-input-widget--text-input--4-Mx-" value="A6" style="width: 100%; height: 100%;"></span></div></div></form>`;
var form0207= `<form><div class="image-form-question--image-container--3HTvR" style="position: relative;"><img src="https://lh4.ggpht.com/mM-dPjHaqFbaF_pjDkg5u404ECxPDV_zbiC4r6Au1ZQb7O5_urtXS7jUuXUi1SOcutgHcK9Y3O8S4Kqt0TPi=s0#w=1280&amp;h=720" style="width: 100%; max-height: 100%;"><div style="top: 41.0438%; left: 3.83919%; position: absolute; width: 27.2069%; height: 7.45501%;"><span class="text-input-widget--container--2JE4b"><label for="text-0" class="text-input-widget--label--D9NOV">Empty</label><input name="0" type="text" id="text-0" class="text-input-widget--text-input--4-Mx-" value="=Sum(A1:A6)" style="width: 100%; height: 100%;"></span></div></div></form>`;
var form0208= `<form><div class="image-form-question--image-container--3HTvR" style="position: relative;"><img src="https://lh3.ggpht.com/lCy8VqtTZ-8TqJY33H5qP5LYyqrXDMzRUTrX9-duuKejt-aXOgZZhUz2p-_m_eAfTfO2gt4lLbIA6E3YvWKQ=s0#w=1280&amp;h=720" style="width: 100%; max-height: 100%;"><div style="top: 83.5696%; left: 50.2354%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-0" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-0" class="radio-button-widget--radio--ws3E_" value="0"></span></div><div style="top: 91.8814%; left: 55.6682%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-1" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-1" class="radio-button-widget--radio--ws3E_" value="1"></span></div><div style="top: 92.268%; left: 46.6498%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-2" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-2" class="radio-button-widget--radio--ws3E_" value="2"></span></div><div style="top: 92.0747%; left: 42.3035%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-3" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-3" class="radio-button-widget--radio--ws3E_" value="3"></span></div></div></form>`;
var form0209= `<form><div class="image-form-question--image-container--3HTvR" style="position: relative;"><img src="https://lh6.ggpht.com/89dycgnXMLDKkWZu0Ljxh8uyPjlLzfxQhNTnGgoyfynq5le5zIPTgUbK9VGCfv2Slbtxm-w193QfFS3fQuw=s0#w=1280&amp;h=720" style="width: 100%; max-height: 100%;"><div style="top: 55.9278%; left: 32.9591%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-0" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-0" class="radio-button-widget--radio--ws3E_" value="0"></span></div><div style="top: 46.0696%; left: 32.4158%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-1" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-1" class="radio-button-widget--radio--ws3E_" value="1"></span></div></div></form>`;
var form0210= `<form><div class="image-form-question--image-container--3HTvR" style="position: relative;"><img src="https://lh5.ggpht.com/g0H4wJrjKLfVt-avPPGVvDgAJ_4uSBRNtjtkkc25ajFR3ZOUTihbDCmxgXMrw7s8B2lVgIxKTGEVIAXXpQ=s0#w=1280&amp;h=720" style="width: 100%; max-height: 100%;"><div style="top: 42.9768%; left: 33.5024%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-0" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-0" class="radio-button-widget--radio--ws3E_" value="0"></span></div><div style="top: 34.085%; left: 33.1764%; position: absolute; width: 0%; height: 0%; max-width: 15px; max-height: 15px;"><span><label for="radio-1" class="radio-button-widget--label--vDh18">Empty</label><input type="radio" name="group0" id="radio-1" class="radio-button-widget--radio--ws3E_" value="1"></span></div></div></form>`;
var form02= [ form0201, form0202, form0203, form0204, form0205, form0206, form0207, form0208, form0209, form0210 ];

